version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:5000"
    environment:
      - ENVIRONMENT=local
      - APP_VERSION=1.0.0
      - DEPLOY_TIME=2025-01-01 12:00:00
    restart: unless-stopped