name: Rollback Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to rollback'
        required: true
        type: choice
        options:
          - staging
          - production
      previous_version:
        description: 'Previous version/tag to rollback to'
        required: true
        type: string

jobs:
  rollback:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
    - name: Rollback deployment
      run: |
        echo "🔄 Rolling back ${{ github.event.inputs.environment }} to version ${{ github.event.inputs.previous_version }}"
        echo "Simulating rollback process..."
        sleep 5
        echo "✅ Rollback completed successfully!"

    - name: Verify rollback
      run: |
        echo "🧪 Verifying rollback..."
        echo "✅ Rollback verification passed!"

    - name: Notify rollback
      run: |
        echo "📢 Rollback completed!"
        echo "Environment: ${{ github.event.inputs.environment }}"
        echo "Rolled back to: ${{ github.event.inputs.previous_version }}"